---
sidebar: sidebar 
permalink: task-add-gcp-bucket.html 
keywords: google cloud storage buckets, google cloud storage, add buckets 
summary: 'Google Cloud Storage システムが [システム] ページで利用可能になると、 NetApp Consoleから直接バケットを追加できます。' 
---
= Google Cloud Storage バケットを追加する
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Google Cloud Storage システムが [システム] ページで利用可能になると、 NetApp Consoleから直接バケットを追加できます。

.手順
. [システム] ページで、Google Cloud Storage システムをダブルクリックして Google Cloud Storage バケットの概要ページを表示し、[*バケットを追加*] をクリックします。
+
_バケットの追加_ ページが表示されます。

. _プロジェクトの詳細_セクションに必要な情報を入力します。
+
** *バケット名* - バケットに使用する名前を入力します。 https://cloud.google.com/storage/docs/buckets#naming["命名要件については、Google Cloud のドキュメントをご覧ください。"^] 。
** *Google プロジェクト* - バケットの所有者となる Google プロジェクトを選択します。これは、コンソール エージェントがデプロイされたプライマリ プロジェクトにすることも、別のプロジェクトにすることもできます。ドロップダウン リストに追加のプロジェクトが表示されない場合は、 NetApp Consoleサービス アカウントが他のプロジェクトにまだ関連付けられていません。  Google Cloud コンソールに移動し、IAM サービスを開いて、プロジェクトを選択します。 NetApp Consoleロールを持つサービス アカウントをそのプロジェクトに追加します。プロジェクトごとにこの手順を繰り返す必要があります。注: これはNetApp Console用に設定したサービスアカウントです。 https://docs.netapp.com/us-en/console-setup-admin/task-set-up-permissions-google.html#set-up-permissions-for-the-connector["このページに記載されている通り"^] 。
** *ラベル* - ラベルは、Google Cloud リソースのメタデータです。バケットを作成するときに、最大 10 個のラベル キー:値ペアを追加できます。https://cloud.google.com/compute/docs/labeling-resources["ラベルの詳細については、Google Cloud のドキュメントをご覧ください。"^] 。


. _Location_ セクションで、バケットが作成されるロケーション タイプとリージョン (複数可) を選択します。  3 つの異なるタイプの場所から選択できます。
+
[cols="35,65"]
|===
| 「場所の種類」を選択した場合... | 次に選択します... 


| リージョン | 「利用可能なリージョン」フィールドからの単一のリージョン。 


| デュアルリージョン  a| 
「利用可能な場所」フィールドから地理的な場所 (単一の大陸) を選択し、「利用可能な地域」フィールドで 2 つの地域を選択します。

15 分以内に新しく書き込まれたすべてのオブジェクトの地理的冗長性を保証する場合は、「ターボ レプリケーション」を有効にできます。



| マルチリージョン | 「利用可能なマルチリージョン」フィールドからの地理的マルチリージョン。 
|===
+
すべての Cloud Storage データは、アップロードされるとすぐに、少なくとも 1 つの地理的な場所内の少なくとも 2 つのゾーンにわたって冗長化されることに注意してください。 https://cloud.google.com/storage/docs/locations["バケットの場所の詳細については、Google Cloud のドキュメントをご覧ください。"^] 。

. _ストレージ クラス_ セクションで、バケット内のオブジェクトに使用するストレージ クラスを選択します。  4 つのストレージ クラスから選択するか、_Autoclass_ を選択して、必要に応じて Google がクラスを調整することもできます。
+
** *標準* - 頻繁にアクセスされるデータ (「ホット」データ) や、短期間のみ保存されるデータに最適です。
** *Nearline* - アクセス頻度の低いデータを保存するための低コストで耐久性の高いストレージ サービス。
** *Coldline* - あまり頻繁にアクセスされないデータを保存するための、非常に低コストで耐久性の高いストレージ サービスです。
** *アーカイブ* - データのアーカイブ、オンライン バックアップ、災害復旧のための、最も低コストで耐久性に優れたストレージ サービスです。
** *Autoclass* - 各オブジェクトのアクセス パターンに基づいて、バケット内のオブジェクトを適切なストレージ クラスに自動的に移行します。
+
コストと取得料金はストレージ クラスごとに異なります。 https://cloud.google.com/storage/docs/storage-classes["ストレージクラスの詳細については、Google Cloud のドキュメントをご覧ください。"^] 。



. [_Protection_] セクションで、バケット内のオブジェクトを保護するためにデータ保護ツールを使用するか、データへのアクセスを保護するためにデータ暗号化構成を使用するかを選択します。
+
*データ保護ツール*

+
** *なし* - デフォルトでは、バケットで保護ツールは有効になっていません。
** *オブジェクトのバージョン管理* - オブジェクトのバージョン管理は、オブジェクトの複数のバージョンを同じバケット内に保持する手段です。バケットは、ライブ オブジェクト バージョンを更新、置換、または削除するたびに、非最新のオブジェクト バージョンを保持し、オブジェクトの保護されたバージョンを継続的に維持します。  「オブジェクトのバージョン管理」を選択すると、次の 2 つのオプションを指定できます。
+
*** *オブジェクトあたりの最大バージョン数* - 作成されるオブジェクトあたりの非最新バージョンの数を入力します。
*** *非最新バージョンの有効期限* - 古い非最新オブジェクトが削除されるまでの日数を入力します。


** *保持ポリシー* - 保持ポリシーにより、バケット内の現在のオブジェクトと将来のオブジェクトはすべて、保持ポリシーで定義した期間に達するまで削除または置換できなくなります。  「保持ポリシー」を選択すると、次の 2 つのオプションを指定できます。
+
*** *オブジェクトの保持期間* - オブジェクトを保持する秒数、日数、月数、または年数を入力します。
*** *時間枠* - 時間の単位を秒、日、月、年のいずれかから選択します。
+
オブジェクトのバージョン管理ツールと保持ポリシー保護ツールを同時に有効にすることはできません。  Google Cloudのドキュメントをご覧ください https://cloud.google.com/storage/docs/object-versioning["オブジェクトのバージョン管理に関する詳細情報"^]、 そして https://cloud.google.com/storage/docs/bucket-lock["保持ポリシーに関する詳細情報"^]。





+
*データ暗号化ツール*

+
** *Google 管理の暗号化キー* - デフォルトでは、Google 管理の暗号化キーがデータの暗号化に使用されます。
** *顧客管理の暗号化キー* - デフォルトの Google 管理の暗号化キーの代わりに、独自の顧客管理キーを使用してデータを暗号化できます。独自の顧客管理キーを使用する予定の場合は、このページでキーを選択できるように、事前にキーを作成しておく必要があります。
+
キーはバケットと同じプロジェクトに配置することも、別のプロジェクトを選択することもできます。

+
Google Cloudのドキュメントをご覧ください https://cloud.google.com/storage/docs/encryption/default-keys["Google が管理する暗号化キーに関する詳細情報"^]、 そして https://cloud.google.com/storage/docs/encryption/customer-managed-keys["顧客管理暗号化キーの詳細情報"^]。



. *追加*をクリックするとバケットが作成されます。

